# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreateLayerFromSelectedFeatures
                                 A QGIS plugin
 This plugin creates a layer using selected features.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-06
        copyright            : (C) 2021 by Murat Çalışkan
        email                : caliskan.murat.20@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CreateLayerFromSelectedFeatures class from file CreateLayerFromSelectedFeatures.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .create_layer_from_selected_features import CreateLayerFromSelectedFeatures
    return CreateLayerFromSelectedFeatures(iface)
